name: 'Generate DBT Docs'
description: 'Generates DBT docs for single or multiple projects'
author: 'Praneeth Kumar Reddy Ballarapu (praneeth527)'

branding:
  icon: 'book-open'
  color: 'orange'

inputs:
  projects_dir:
    description: 'path of the dbt projects folder in the repo'
    required: true
  docs_dir:
    description:
      'output directory path where dbt generated docs will be written'
    required: true
    default: 'docs'
  env_file_path:
    description: 'env variables file to source before running dbt commands'
    required: false
  dbt_profile:
    description: 'dbt profile to be passed to the dbt command'
    required: false
  dbt_vars:
    description: 'dbt vars to be passed to the dbt command'
    required: false
  dbt_target:
    description: 'dbt target to be passed to the dbt command'
    required: false

runs:
  using: node20
  main: dist/index.js
